### PR TITLE
Ability to specify config via yaml file

### LINKED ISSUE #94: Feature request: Add a mechanism to specify configuration
The current implementation uses command line switches to control the configuration of the chartmuseum. This will become very hard to maintain and or implement if we want to support per tenant configurations.

We could add a configuration file to allow varying options for the chartmuseum startup.

### PR DESCRIPTION
**Pull request by jdolitsky**
Fixes #94. Is a prerequisite for #93 and #86.

Added the ability to specify a yaml config file using the `-c/--config` flag.

The order of configuration variable overrides is the following:

- config file
- environment variable
- command line flag

Uses the [viper](https://github.com/spf13/viper) package to parse the configuration. Viper allows for remote configuration in both etcd and Consul, which will become important to support users who want to change repo-specific config on-the-fly (public vs private repo etc).

### CODE REVIEW

**Comment by jdolitsky** [comment]
cc @itaysk @goruha

**Comment by goruha** [comment]
@jdolitsky I think that using https://github.com/spf13/cobra can simplify code alot.
It have perfect integration with viper

**Comment by jdolitsky** [comment]
@goruha I was looking at that as well. I think we probably should switch
from cli to cobra if we’re using viper.

So you think then that viper is the appropriate library to use here for
per-repo configuration? Is etcd/consul a good place to keep this info?

**Comment by jdolitsky** [comment]
@goruha I've opened #100 for the switch. Feel free to take a stab :)

**Pull request merged**
