### PR TITLE
if directories does not exists, create it

### PR DESCRIPTION
**Pull request by samifruit514**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by samifruit514** [comment]
fixed my email.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @samifruit514 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by samifruit514** [comment]
fix email strike 2

**Comment by jdolitsky** [comment]
This looks good to me! happy to merge when this CLA situation is fixed

**Comment by samifruit514** [comment]
strike 3

**Comment by jdolitsky** [comment]
Fixes #102

**Comment by samifruit514** [comment]
thanks a lot!

**Pull request merged**
