### PR TITLE
Support for Alibaba Cloud OSS storage backend

### PR DESCRIPTION
**Pull request by denverdino**
Signed-off-by: Li Yi <denverdino@gmail.com>

### CODE REVIEW

**Comment by denverdino** [comment]
Rebase to latest commit

**Comment by xianlubird** [comment]
@jdolitsky Any update?

**Comment by jdolitsky** [comment]
Hi, apologies on delay. will check this out tomorrow

**Comment by jdolitsky** [comment]
@denverdino worked very well! Just had to add some stuff around tests etc. Thanks again!!

**Comment by jdolitsky** [comment]
@denverdino @xianlubird this is now in v0.4.0

**Comment by denverdino** [comment]
Thanks a lot!

**Pull request merged**
