### PR TITLE
Webhook impelemtation

### PR DESCRIPTION
**Pull request by olegsu**
This PR related to [#83](https://github.com/kubernetes-helm/chartmuseum/issues/83)
This is not a merge candidate but get feedback asap.

* Add event emitter and event handles basic implementation. Considering to use [olebedev/emitter](https://github.com/olebedev/emitter)

* Add implementation of in-memory integration storage.

* Implement webhook HTTP POST request logic includes HMAC header as payload signed by given secret key

* Add end-points to Create, Delete and Get integrations

* TBD:
  * More complex Integration CRUD
  * sql implementation as well
  * Tests

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @olegsu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @olegsu isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jdolitsky** [comment]
@olegsu awesome! looking at asap

**Comment by jdolitsky** [comment]
@olegsu closing this re: our chat. Parts of this should be resubmitted after we have ability to update config per-tenant

**Comment by hhstu** [comment]
hi, why close it ? I think  it`s  useful @jdolitsky

**Pull request closed without merging**
